name: GitHub commit action
on:
  push:
  pull_request:
jobs:
  UnitTest:
    runs-on: ubuntu-latest
    env:
      FUSIONSOLAR_USER: ${{ secrets.FUSIONSOLAR_USER }}
      FUSIONSOLAR_PASSWORD: ${{ secrets.FUSIONSOLAR_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: ./.github/actions/setup_python
      - name: Test
        run: python3 -m unittest discover
      - name: HowTo
        run: python3 how_to.py
  Publish:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: UnitTest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: ./.github/actions/setup_python
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build package
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
      - name: Publish distribution to PyPI
        if: github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
